///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LoginRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("41404e4b-fb1b-4fa7-a9fd-b7ef1153dc36")]
    public partial class LoginRepository : RepoGenBaseFolder
    {
        static LoginRepository instance = new LoginRepository();
        LoginRepositoryFolders.ConnectionManagerAppFolder _connectionmanager;

        /// <summary>
        /// Gets the singleton class instance representing the LoginRepository element repository.
        /// </summary>
        [RepositoryFolder("41404e4b-fb1b-4fa7-a9fd-b7ef1153dc36")]
        public static LoginRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LoginRepository() 
            : base("LoginRepository", "/", null, 0, false, "41404e4b-fb1b-4fa7-a9fd-b7ef1153dc36", ".\\RepositoryImages\\LoginRepository41404e4b.rximgres")
        {
            _connectionmanager = new LoginRepositoryFolders.ConnectionManagerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("41404e4b-fb1b-4fa7-a9fd-b7ef1153dc36")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ConnectionManager folder.
        /// </summary>
        [RepositoryFolder("ebf974ef-07dd-43ff-9c26-e6728b545b36")]
        public virtual LoginRepositoryFolders.ConnectionManagerAppFolder ConnectionManager
        {
            get { return _connectionmanager; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class LoginRepositoryFolders
    {
        /// <summary>
        /// The ConnectionManagerAppFolder folder.
        /// </summary>
        [RepositoryFolder("ebf974ef-07dd-43ff-9c26-e6728b545b36")]
        public partial class ConnectionManagerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _languageInfo;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new ConnectionManager  folder.
            /// </summary>
            public ConnectionManagerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ConnectionManager", "/dom[@domain='testgames.be']", parentFolder, 30000, null, false, "ebf974ef-07dd-43ff-9c26-e6728b545b36", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "b710d00b-7bcd-45b8-8014-56b47f9a17fa");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "c83316d1-d239-4f5f-b309-cead2923117f");
                _languageInfo = new RepoItemInfo(this, "Language", ".//div[#'login']/select[@name='language']", 30000, null, "faf9b4f3-9694-49b7-afec-82140b146f6b");
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//div[#'login']/table//td[@innertext~'^<label>log\\ in</label>']/?/?/label[@innertext='log in']", 30000, null, "215937bc-ebcd-42d3-810d-72bc31efe5d9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ebf974ef-07dd-43ff-9c26-e6728b545b36")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ebf974ef-07dd-43ff-9c26-e6728b545b36")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("b710d00b-7bcd-45b8-8014-56b47f9a17fa")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("b710d00b-7bcd-45b8-8014-56b47f9a17fa")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("c83316d1-d239-4f5f-b309-cead2923117f")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("c83316d1-d239-4f5f-b309-cead2923117f")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Language item.
            /// </summary>
            [RepositoryItem("faf9b4f3-9694-49b7-afec-82140b146f6b")]
            public virtual Ranorex.SelectTag Language
            {
                get
                {
                    return _languageInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Language item info.
            /// </summary>
            [RepositoryItemInfo("faf9b4f3-9694-49b7-afec-82140b146f6b")]
            public virtual RepoItemInfo LanguageInfo
            {
                get
                {
                    return _languageInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("215937bc-ebcd-42d3-810d-72bc31efe5d9")]
            public virtual Ranorex.LabelTag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("215937bc-ebcd-42d3-810d-72bc31efe5d9")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}