///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WelcomePage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WelcomePageRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("f5eb3a7f-e74d-461f-8b6b-7b1491ce3a3f")]
    public partial class WelcomePageRepository : RepoGenBaseFolder
    {
        static WelcomePageRepository instance = new WelcomePageRepository();

        /// <summary>
        /// Gets the singleton class instance representing the WelcomePageRepository element repository.
        /// </summary>
        [RepositoryFolder("f5eb3a7f-e74d-461f-8b6b-7b1491ce3a3f")]
        public static WelcomePageRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WelcomePageRepository() 
            : base("WelcomePageRepository", "/", null, 0, false, "f5eb3a7f-e74d-461f-8b6b-7b1491ce3a3f", ".\\RepositoryImages\\WelcomePageRepositoryf5eb3a7f.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f5eb3a7f-e74d-461f-8b6b-7b1491ce3a3f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class WelcomePageRepositoryFolders
    {
    }
#pragma warning restore 0436
}